.TH WORMHOLE-RS "1" "May 2024" "wormhole-rs 0.6.1" "User Commands"
.SH NAME
wormhole-rs \- manual page for wormhole-rs 0.6.1
.SH DESCRIPTION
wormhole\-rs 0.6.1
.SS "USAGE:"
.IP
wormhole\-rs [OPTIONS] <SUBCOMMAND>
.SS "OPTIONS:"
.TP
\fB\-h\fR, \fB\-\-help\fR
Print this help message
.TP
\fB\-v\fR, \fB\-\-verbose\fR
Enable logging to stdout, for debugging purposes
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version information
.SS "SUBCOMMANDS:"
.TP
forward
Forward ports from one machine to another
.TP
receive
Receive a file or a folder [aliases: rx]
.TP
send
Send a file or a folder [aliases: tx]
.TP
send\-many
Send a file to many recipients. READ HELP PAGE FIRST!
.PP
Run a subcommand with `\-\-help` to know how it's used.
To send files, use `wormhole send <PATH>`.
To receive files, use `wormhole receive <CODE>`.
.SH AUTHOR
.TP
Matthias Geiger <werdahias@riseup.net>
.SH COPYRIGHT
.PP
Copyright \[co] 2024 Matthias Geiger
.PP
This manual page was written for the Debian system (and may be used by
others).
.PP
Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU General Public License, Version 3 or (at your
option) any later version published by the Free Software Foundation.
